/* automatically generated by cbindgen */

#ifndef LIBMPV_WRAPPER_H
#define LIBMPV_WRAPPER_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct MpvHandle MpvHandle;

/**
 * Callback function type for mpv events.
 *
 * @param event A JSON string representing the event.
 * @param userdata The user-supplied pointer passed to `mpv_wrapper_create`.
 */
typedef void (*EventCallback)(const char *event, void *userdata);

/**
 * Creates a new mpv handle.
 *
 * @param initial_options A JSON string of initial mpv options (e.g., `{"idle": "yes"}`).
 * @param observed_properties A JSON string mapping property names to their formats (e.g., `{"pause": "flag"}`).
 *                            The format can be "string", "flag", "int64", "double", or "node".
 * @param event_callback A function pointer that will be called for mpv events.
 * @param event_userdata A user-supplied pointer that will be passed to the event_callback.
 * @return A pointer to the opaque mpv handle, or NULL on failure.
 */
struct MpvHandle *mpv_wrapper_create(const char *initial_options,
                                     const char *observed_properties,
                                     EventCallback event_callback,
                                     void *event_userdata);

/**
 * Destroys the mpv handle and terminates the mpv core.
 *
 * @param handle A valid pointer to the mpv handle (obtained from `mpv_wrapper_create`).
 */
void mpv_wrapper_destroy(struct MpvHandle *handle);

/**
 * Executes an mpv command.
 *
 * @param handle A valid pointer to the mpv handle.
 * @param name The name of the command (e.g., "set", "loadfile").
 * @param args A JSON string representing an array of arguments (e.g., `["volume", "50"]`, `["path/to/video.mp4"]`).
 *             Pass an empty string "[]" or NULL for no arguments.
 * @return A JSON string representing the command result (e.g., `{"data": null}` or `{"error": "..."}`).
 *         The caller MUST free this string using `mpv_wrapper_free_string`.
 */
char *mpv_wrapper_command(struct MpvHandle *handle,
                          const char *name,
                          const char *args);

/**
 * Sets an mpv property.
 *
 * @param handle A valid pointer to the mpv handle.
 * @param name The name of the property to set (e.g., "pause").
 * @param value A JSON string representing the value (e.g., "true").
 * @return A JSON string indicating success or failure.
 *         The caller MUST free this string using `mpv_wrapper_free_string`.
 */
char *mpv_wrapper_set_property(struct MpvHandle *handle, const char *name, const char *value);

/**
 * Gets an mpv property.
 *
 * @param handle A valid pointer to the mpv handle.
 * @param name The name of the property to get.
 * @param format The format can be "string", "flag", "int64", "double", or "node".
 * @return A JSON string containing the property value (e.g., `{"data": true}`) or an error.
 *         The caller MUST free this string using `mpv_wrapper_free_string`.
 */
char *mpv_wrapper_get_property(struct MpvHandle *handle, const char *name, const char *format);

/**
 * Frees a C string that was returned by one of the `mpv_wrapper_*` functions.
 *
 * @param s A pointer to the C string to be freed.
 */
void mpv_wrapper_free(char *s);

#endif  /* LIBMPV_WRAPPER_H */
